trigger:
  branches:
    include:
      - main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'res'
  location: 'East US'  # Update as per your requirement

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureSubscription: 'AzureSubConnection'  # Name of your Azure service connection
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'  # The existing resource group "res"
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(System.DefaultWorkingDirectory)/infrastructure/templates/sql-database-template.json'  # Path to the ARM template
      csmParametersFile: '$(System.DefaultWorkingDirectory)/infrastructure/templates/sql-database-parameters.json'  # Path to parameters file
      deploymentMode: 'Incremental'
