trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerName: 'mySqlServer'
  sqlDatabaseName: 'mydatabase'
  sqlAdminUser: 'adminuser'
  sqlAdminPassword: 'password@123'
  azureSubscription: '<Your-Service-Connection-Name>'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az sql db execute --server $(sqlServerName) --name $(sqlDatabaseName) --admin-user $(sqlAdminUser) --admin-password $(sqlAdminPassword) --query "$(cat $(System.DefaultWorkingDirectory)/create_table.sql)"
  displayName: 'Execute SQL Script'
