trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerName: 'mySqlServer'
  sqlDatabaseName: 'mydatabase'
  sqlAdminUser: 'adminuser'
  sqlAdminPassword: 'password@123'
  location: 'East US'
  resourceGroupName: 'myResourceGroup'
  azureSubscription: 'Infra and Code pipline'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureSubscription)'
    action: 'Create Or Update Resource Group Deployment'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/Azure%20Infra%20and%20code%20pipeline/Infradeploy.json'
    deploymentMode: 'Incremental'
    parameters: |
      sqlServerName=$(sqlServerName)
      sqlAdminLogin=$(sqlAdminUser)
      sqlAdminPassword=$(sqlAdminPassword)
      sqlDatabaseName=$(sqlDatabaseName)
      location=$(location)
